---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rox-pipeline-with-m2m
spec:

  workspaces:
    - name: shared-workspace
    #- name: roxctl-config

  params:
    - name: deployment-name
      type: string
      description: name of the deployment resource to be patched
    - name: deployment
      type: string
      description: filename of the deployment to be patched
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: main
    - name: IMAGE
      type: string
      description: image to be build from the code
    - name: rox_central_endoint
      type: string
      description: The address:port tuple for RHACS Stackrox Central.
      default: central.stackrox.svc:443

  tasks:
    - name: enable-workspace-write
      taskRef:
        name: enable-write-on-workspace
        kind: Task
      workspaces:
        - name: workspace
          workspace: shared-workspace

    - name: rhacs-authenticate
      taskRef:
        name: rhacs-m2m-exchange
        kind: Task
      params:
        - name: insecure-skip-tls-verify
          value: "true"
        - name: rox_config_subdir
          value: roxctl-config
        - name: rox_token_file
          value: rox_api_token
      workspaces:
        - name: roxctl-config
          workspace: shared-workspace
      runAfter:
      - enable-workspace-write

    # checkout source code
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
      - name: output
        workspace: shared-workspace
      params:
      - name: url
        value: $(params.git-url)
      - name: subdirectory
        value: ""
      - name: deleteExisting
        value: "true"
      - name: revision
        value: $(params.git-revision)
      runAfter:
      - rhacs-authenticate

    # validate deployment against defined  RHACS policies
    - name: police-deployment
      taskRef:
        name: rhacs-deployment-check
        kind: Task
      workspaces:
      - name: source
        workspace: shared-workspace
      - name: roxctl-config
        workspace: shared-workspace
      params:
      - name: deployment
        value: $(params.deployment)
      - name: insecure-skip-tls-verify
        value: "true"
      - name: roxctl-config-subdir
        value: roxctl-config
      - name: rox_token_file
        value: rox_api_token
      runAfter:
      - fetch-repository

    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
      - name: IMAGE
        value: $(params.IMAGE)
      - name: TLSVERIFY
        value: "false"
      workspaces:
      - name: source
        workspace: shared-workspace
      runAfter:
      - fetch-repository

    # scan image for vulns using RHACS
    - name: scan-image
      taskRef:
        name: rhacs-image-scan
        kind: Task
      workspaces:
      - name: roxctl-config
        workspace: shared-workspace
      params:
      - name: image
        value: "$(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST)"
      - name: insecure-skip-tls-verify
        value: "true" # stackrox to OCP image registry x509 fail...
      - name: roxctl-config-subdir
        value: roxctl-config
      - name: rox_token_file
        value: rox_api_token
      runAfter:
      - build-image

    # validate image against RHACS policies
    - name: police-image
      taskRef:
        name: rhacs-image-check
        kind: Task
      workspaces:
      - name: roxctl-config
        workspace: shared-workspace
      params:
      - name: image
        value: "$(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST)"
      - name: insecure-skip-tls-verify
        value: "true"
      - name: roxctl-config-subdir
        value: roxctl-config
      - name: rox_token_file
        value: rox_api_token
      runAfter:
      - scan-image
