---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rhacs-deployment-check
  labels:
    app.kubernetes.io/version: "3.71"
  annotations:
    tekton.dev/tags: security
    tekton.dev/categories: Security
    tekton.dev/displayName: "Policy check a deployment with Red Hat Advanced Cluster Security"
    tekton.dev/platforms: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,darwin/amd64,darwin/arm64,windows/amd64"
    tekton.dev/pipelines.minVersion: "0.18.0"
spec:
  description: >-
    Policy check a deployment with Red Hat Advanced Cluster Security.

    This tasks allows you to check a Kubernetes deployment manifest against policies
    and apply enforcement to fail pipelines.
  params:
    - name: rox_central_endpoint
      type: string
      description: The address:port tuple for RHACS Stackrox Central.
      default: central.stackrox.svc:443
    - name: rox_image
      description: Image providing the roxctl tool.
      default: quay.io/stackrox-io/roxctl:3.71.0
    - name: deployment
      type: string
      description: |
        Deployment filename to check.
        Examples: 'deployment.yaml', '$(workspaces.source.path)/base/deployment.yaml'
      default: '$(workspaces.source.path)/deployment.yaml'
    - name: output_format
      description: Results output format (csv | json | junit | table)
      type: string
      default: "table"
    - name: insecure-skip-tls-verify
      type: string
      description: |
        Do not verify TLS certificates.

        When set to "true", skip verifying the TLS certs of the Central endpoint and registry.
      default: "false"
    - name: rox_config_dir
      type: string
      description: |
        Path to the roxtl config directory within the roxctl-config workspace (if machine to machine authentication is used).
        Mutually exclusive with token_file.
        The path should be prefixed with "/roxctl-config".
      default: ""
    - name: rox_token_file
      description: |
        Path to the API Token file (if authentication through API token).
        Mutually exclusive with rox_config_dir.
        The path should be prefixed with "/rox-api-auth-token".
        Example "/rox-api-auth-token/rox_api_token"
      type: string
      default: ""
  workspaces:
    - name: source
    - name: roxctl-config
      description: |
        A workspace containing the configuration for roxctl. Used to authenticate with the remote central using short-lived tokens.
        Mutually exclusive with rox-api-token-auth workspace.
        The workspace is ideally populated by a rhacs-m2m-authenticate TaskRun.
      optional: true
      readOnly: true
      mountPath: /roxctl-config
    - name: rox-api-token-auth
      description: |
        A workspace containing a rox token file. Used to authenticate with the remote central.
        Mutually exclusive with roxctl-config.
        It is strongly recommended that this workspace be bound to a Kubernetes secret.
      optional: true
      readOnly: true
      mountPath: /rox-api-token-auth
  results:
    - name: check_output
      description: Output of `roxctl deployment check`
  steps:
    - name: rox-deploy-check
      image: $(params.rox_image)
      workingDir: $(workspaces.source.path)
      env:
        - name: DEPLOYMENT
          value: $(params.deployment)
        - name: HOME
          value: /tekton/home
        - name: INSECURE
          value: $(params.insecure-skip-tls-verify)
        - name: OUTPUT
          value: $(params.output_format)
        - name: ROX_CONFIG_DIR
          value: $(params.rox_config_dir)
        - name: ROX_API_TOKEN_FILE
          value: $(params.rox_token_file)
        - name: ROX_ENDPOINT
          value: $(params.rox_central_endpoint)
      args:
        - deployment
        - check
        - --insecure-skip-tls-verify=$(INSECURE)
        - --output=$(OUTPUT)
        - --file=$(DEPLOYMENT)
