---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rhacs-m2m-exchange
  labels:
    apps.kubernetes.io/version: "4.5"
  annotations:
    tekton.dev/tags: security
    tekton.dev/categories: Security
    tekton.dev/displayName: "Exchange a service account token for a Red Hat Advanced Cluster Security short-lived token"
    tekton.dev/platforms: "linux/amd64"
    tekton.dev/pipelines.minVersion: "0.18.0"
spec:
  description: >-
    Exchanges a kubernetes service account token against a Red Hat Advanced Cluster Security short-lived token.

    This task allows you to fetch a Red Hat Advanced Cluster Security token for use in other `rhacs-*` tasks.
  workspaces:
    - name: roxctl-config
      mountPath: /roxctl-config
  params:
    - name: rox_image
      description: Image providing the roxctl tool.
      default: 'quay.io/stackrox-io/roxctl:4.4.x-376-g3a3364f8d6'
    - name: rox_central_endpoint
      description: The address:port tuple for RHACS Stackrox Central.
      type: string
      default: central.stackrox.svc:443
    - name: insecure-skip-tls-verify
      description: |
        Do not verify TLS certificates.

        When set to "true", skip verifying the TLS certs of the Central endpoint and registry.
      type: string
      default: "false"
    - name: rox_config_dir
      type: string
      description: |
        Path to the roxtl config directory within the roxctl-config workspace.
        The path should be prefixed with /roxctl-config .
      default: ""
  stepTemplate:
    env:
      - name: HOME
        value: /tekon/home
      - name: INSECURE
        value: $(params.insecure-skip-tls-verify)
      - name: ROX_ENDPOINT
        value: $(params.rox_central_endpoint)
      - name: ROX_CONFIG_DIR
        value: $(params.rox_config_dir)
  steps:
    - name: exchange-service-account-token
      image: $(params.rox_image)
      volumeMounts:
        - name: token-vol
          mountPath: /service-account-token
      args:
        - central
        - m2m
        - exchange
        - --insecure-skip-tls-verify=$(INSECURE)
        - --token-file=/service-account-token/token
  volumes:
    - name: token-vol
      projected:
        sources:
          - serviceAccountToken:
              audience: rhacs
              path: token
              expirationSeconds: 3600

